# Generated by Django 5.0.6 on 2024-05-31 18:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Enter a location', 'unique': 'Enter a unique location'}, help_text='Enter a location name', max_length=255, verbose_name='Location name')),
                ('latitude', models.FloatField(error_messages={'blank': 'Enter a latitude'}, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(error_messages={'blank': 'Enter a longitude'}, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ['name', 'latitude', 'longitude'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'Enter a title'}, help_text='Enter a title', max_length=255, verbose_name='Post title')),
                ('content', models.TextField(error_messages={'blank': 'Enter post text'}, help_text='Enter post text', verbose_name='Post text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Post created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Post updated at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_media', verbose_name='Post image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post author')),
                ('location', models.ForeignKey(error_messages={'blank': 'Enter post location'}, on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='Post location')),
            ],
            options={
                'verbose_name': 'Post',
                'ordering': ['title', 'created_at', 'updated_at', 'location', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(error_messages={'blank': 'Enter comment'}, verbose_name='Comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comment author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Under which post is comment under')),
            ],
            options={
                'verbose_name': 'Comment',
                'ordering': ['created_at', 'author', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
            options={
                'verbose_name': 'Like',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
