# Generated by Django 5.0.6 on 2024-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(error_messages={'blank': 'Enter a location', 'unique': 'Enter a unique location'}, max_length=255, verbose_name='Location name'),
        ),
    ]
